name: Deploy to Github Pages
on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - master  # Trigger deploy on 'master' branch
      - gh-pages  # Trigger deploy on 'gh-pages' branch
  workflow_dispatch:
    # Allow manual trigger of the workflow with optional Hugo version input
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.125.7"
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
# Default to bash shell for running commands
defaults:
  run:
    shell: bash
# Set permissions of GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.125.7' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master  # Ensure the workflow checks out the 'master' branch
          submodules: recursive  # Simplify theme initialization
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
      - name: Build with Hugo
        run: |
          hugo \
            --buildDrafts --gc \
            --baseURL ${{ steps.pages.outputs.base_url }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./public  # The directory Hugo generates the site in
          name: github-pages  # Explicitly name the artifact
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages  # Match the artifact name from the upload step